name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -U --upgrade pip
        pip install -U --only-binary=numpy -r REQUIREMENTS.txt
        pip install -r REQUIREMENTS.txt  
    - name: Run "check.sh"
      run: ./check.sh
